dist: trusty
sudo: required
language: python
cache: pip
services:
  - postgresql

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO=1.7 PG=9.2
  - DJANGO=1.7 PG=9.3
  - DJANGO=1.7 PG=9.4
  - DJANGO=1.7 PG=9.5
  - DJANGO=1.7 PG=9.6
  - DJANGO=1.7 PG=10
  - DJANGO=1.8 PG=9.2
  - DJANGO=1.8 PG=9.3
  - DJANGO=1.8 PG=9.4
  - DJANGO=1.8 PG=9.5
  - DJANGO=1.8 PG=9.6
  - DJANGO=1.8 PG=10
  - DJANGO=1.9 PG=9.2
  - DJANGO=1.9 PG=9.3
  - DJANGO=1.9 PG=9.4
  - DJANGO=1.9 PG=9.5
  - DJANGO=1.9 PG=9.6
  - DJANGO=1.9 PG=10
  - DJANGO=1.10 PG=9.2
  - DJANGO=1.10 PG=9.3
  - DJANGO=1.10 PG=9.4
  - DJANGO=1.10 PG=9.5
  - DJANGO=1.10 PG=9.6
  - DJANGO=1.10 PG=10
  - DJANGO=1.11 PG=9.2
  - DJANGO=1.11 PG=9.3
  - DJANGO=1.11 PG=9.4
  - DJANGO=1.11 PG=9.5
  - DJANGO=1.11 PG=9.6
  - DJANGO=1.11 PG=10
  - DJANGO=2.0 PG=9.2
  - DJANGO=2.0 PG=9.3
  - DJANGO=2.0 PG=9.4
  - DJANGO=2.0 PG=9.5
  - DJANGO=2.0 PG=9.6
  - DJANGO=2.0 PG=10
  - DJANGO=2.1 PG=9.2
  - DJANGO=2.1 PG=9.3
  - DJANGO=2.1 PG=9.4
  - DJANGO=2.1 PG=9.5
  - DJANGO=2.1 PG=9.6
  - DJANGO=2.1 PG=10

matrix:
  exclude:
  # Django 2.0+ doesn't support python 2.7
  - python: 2.7
    env: DJANGO=2.0 PG=9.2
  - python: 2.7
    env: DJANGO=2.0 PG=9.3
  - python: 2.7
    env: DJANGO=2.0 PG=9.4
  - python: 2.7
    env: DJANGO=2.0 PG=9.5
  - python: 2.7
    env: DJANGO=2.0 PG=9.6
  - python: 2.7
    env: DJANGO=2.0 PG=10
  - python: 2.7
    env: DJANGO=2.1 PG=9.2
  - python: 2.7
    env: DJANGO=2.1 PG=9.3
  - python: 2.7
    env: DJANGO=2.1 PG=9.4
  - python: 2.7
    env: DJANGO=2.1 PG=9.5
  - python: 2.7
    env: DJANGO=2.1 PG=9.6
  - python: 2.7
    env: DJANGO=2.1 PG=10

  # Django 1.9+ doesn't support python 3.3
  - python: 3.3
    env: DJANGO=1.9 PG=9.2
  - python: 3.3
    env: DJANGO=1.9 PG=9.3
  - python: 3.3
    env: DJANGO=1.9 PG=9.4
  - python: 3.3
    env: DJANGO=1.9 PG=9.5
  - python: 3.3
    env: DJANGO=1.9 PG=9.6
  - python: 3.3
    env: DJANGO=1.9 PG=10
  - python: 3.3
    env: DJANGO=1.10 PG=9.2
  - python: 3.3
    env: DJANGO=1.10 PG=9.3
  - python: 3.3
    env: DJANGO=1.10 PG=9.4
  - python: 3.3
    env: DJANGO=1.10 PG=9.5
  - python: 3.3
    env: DJANGO=1.10 PG=9.6
  - python: 3.3
    env: DJANGO=1.10 PG=10
  - python: 3.3
    env: DJANGO=1.11 PG=9.2
  - python: 3.3
    env: DJANGO=1.11 PG=9.3
  - python: 3.3
    env: DJANGO=1.11 PG=9.4
  - python: 3.3
    env: DJANGO=1.11 PG=9.5
  - python: 3.3
    env: DJANGO=1.11 PG=9.6
  - python: 3.3
    env: DJANGO=1.11 PG=10
  - python: 3.3
    env: DJANGO=2.0 PG=9.2
  - python: 3.3
    env: DJANGO=2.0 PG=9.3
  - python: 3.3
    env: DJANGO=2.0 PG=9.4
  - python: 3.3
    env: DJANGO=2.0 PG=9.5
  - python: 3.3
    env: DJANGO=2.0 PG=9.6
  - python: 3.3
    env: DJANGO=2.0 PG=10
  - python: 3.3
    env: DJANGO=2.1 PG=9.2
  - python: 3.3
    env: DJANGO=2.1 PG=9.3
  - python: 3.3
    env: DJANGO=2.1 PG=9.4
  - python: 3.3
    env: DJANGO=2.1 PG=9.5
  - python: 3.3
    env: DJANGO=2.1 PG=9.6
  - python: 3.3
    env: DJANGO=2.1 PG=10

  # Django 2.1 doesn't support python 3.4
  - python: 3.4
    env: DJANGO=2.1 PG=9.2
  - python: 3.4
    env: DJANGO=2.1 PG=9.3
  - python: 3.4
    env: DJANGO=2.1 PG=9.4
  - python: 3.4
    env: DJANGO=2.1 PG=9.5
  - python: 3.4
    env: DJANGO=2.1 PG=9.6
  - python: 3.4
    env: DJANGO=2.1 PG=10


  # Django 1.7 doesn't support python 3.5+
  - python: 3.5
    env: DJANGO=1.7 PG=9.2
  - python: 3.5
    env: DJANGO=1.7 PG=9.3
  - python: 3.5
    env: DJANGO=1.7 PG=9.4
  - python: 3.5
    env: DJANGO=1.7 PG=9.5
  - python: 3.5
    env: DJANGO=1.7 PG=9.6
  - python: 3.5
    env: DJANGO=1.7 PG=10
  - python: 3.6
    env: DJANGO=1.7 PG=9.2
  - python: 3.6
    env: DJANGO=1.7 PG=9.3
  - python: 3.6
    env: DJANGO=1.7 PG=9.4
  - python: 3.6
    env: DJANGO=1.7 PG=9.5
  - python: 3.6
    env: DJANGO=1.7 PG=9.6
  - python: 3.6
    env: DJANGO=1.7 PG=10

before_install:
  - sudo service postgresql stop && sudo service postgresql start $PG

install:
  - pip install -r requirements.txt
  # .* postfix to install latest minor version, not x.x.0 version of django
  - pip install -q Django==$DJANGO.*
  - python setup.py -q install

before_script:
  - psql -tc 'SHOW server_version' -U postgres
  - psql -c 'CREATE ROLE test;' -U postgres
  - psql -c 'ALTER ROLE test WITH SUPERUSER;' -U postgres
  - psql -c 'ALTER ROLE test WITH LOGIN;' -U postgres
  - psql -c "ALTER ROLE test PASSWORD 'test';" -U postgres
  - psql -c 'CREATE DATABASE test OWNER test;' -U postgres
  - psql -c 'CREATE DATABASE test2 OWNER test;' -U postgres

script:
  python runtests.py
